name: Continuous Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  site:
    runs-on: self-hosted
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      appName: ifocusit
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Build docker image
        run: docker-compose build ${{ env.appName }}
      - name: Publish to registry
        run: |
          echo "docker login ${{ env.registry }} -u ${{ env.username }}"
          echo ${{ env.password }} | docker login ${{ env.registry }} -u ${{ env.username }} --password-stdin
          docker push ${{ env.image }}:latest
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: submarine.banan4.com/ifocusit/${{ env.appName }}-web
          registry: submarine.banan4.com
